services:
  - type: web
    name: mam-tours
    env: php
    buildCommand: bash build.sh
    startCommand: vendor/bin/heroku-php-apache2 public/
    envVars:
      - key: APP_NAME
        value: MAM Tours
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        sync: false
      - key: LOG_CHANNEL
        value: stack
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: mam-tours-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: mam-tours-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: mam-tours-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: mam-tours-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: mam-tours-db
          property: password
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: CACHE_DRIVER
        value: file

databases:
  - name: mam-tours-db
    databaseName: mam_tours
    user: mam_tours_user
